Remove "DEFINE_SYMBOL HESAFF_EXPORTS" from src/cpp/CMakeLists.txt
By defining "HESAFF_EXPORTS", it's causing some dll related errors:

```
../../../src/cpp/hesaff/hesaff.h:13:43: error: ISO C++ forbids declaration of ‘__declspec’ with no type [-fpermissive]
 #define HESAFF_EXPORT __declspec(dllexport)
                                           ^
../../../src/cpp/hesaff/hesaff.cpp:931:25: note: in expansion of macro ‘HESAFF_EXPORT’
 #define PYHESAFF extern HESAFF_EXPORT
                         ^~~~~~~~~~~~~
../../../src/cpp/hesaff/hesaff.cpp:934:1: note: in expansion of macro ‘PYHESAFF’
 PYHESAFF int detect(AffineHessianDetector* detector)
 ^~~~~~~~
../../../src/cpp/hesaff/hesaff.h:13:43: warning: ‘__declspec’ initialized and declared ‘extern’
 #define HESAFF_EXPORT __declspec(dllexport)
                                           ^
```

Removing it fixes this particular problem in a linux docker container and gets
the build further.